//! Model registry auto-generated from packages/ai/src/models.generated.ts
//! Run: node generate-models.mjs

pub fn get_all_models() -> Vec<(&'static str, &'static str, &'static str)> {
    // (id, name, provider)
    vec![
        ("au.anthropic.claude-opus-4-6-v1", "AU Anthropic Claude Opus 4.6", "amazon-bedrock"),
        ("au.anthropic.claude-sonnet-4-6", "AU Anthropic Claude Sonnet 4.6", "amazon-bedrock"),
        ("anthropic.claude-3-haiku-20240307-v1:0", "Claude Haiku 3", "amazon-bedrock"),
        ("anthropic.claude-3-5-haiku-20241022-v1:0", "Claude Haiku 3.5", "amazon-bedrock"),
        ("anthropic.claude-haiku-4-5-20251001-v1:0", "Claude Haiku 4.5", "amazon-bedrock"),
        ("eu.anthropic.claude-haiku-4-5-20251001-v1:0", "Claude Haiku 4.5 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-haiku-4-5-20251001-v1:0", "Claude Haiku 4.5 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-haiku-4-5-20251001-v1:0", "Claude Haiku 4.5 (US)", "amazon-bedrock"),
        ("anthropic.claude-opus-4-20250514-v1:0", "Claude Opus 4", "amazon-bedrock"),
        ("us.anthropic.claude-opus-4-20250514-v1:0", "Claude Opus 4 (US)", "amazon-bedrock"),
        ("anthropic.claude-opus-4-1-20250805-v1:0", "Claude Opus 4.1", "amazon-bedrock"),
        ("us.anthropic.claude-opus-4-1-20250805-v1:0", "Claude Opus 4.1 (US)", "amazon-bedrock"),
        ("anthropic.claude-opus-4-5-20251101-v1:0", "Claude Opus 4.5", "amazon-bedrock"),
        ("eu.anthropic.claude-opus-4-5-20251101-v1:0", "Claude Opus 4.5 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-opus-4-5-20251101-v1:0", "Claude Opus 4.5 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-opus-4-5-20251101-v1:0", "Claude Opus 4.5 (US)", "amazon-bedrock"),
        ("anthropic.claude-opus-4-6-v1", "Claude Opus 4.6", "amazon-bedrock"),
        ("eu.anthropic.claude-opus-4-6-v1", "Claude Opus 4.6 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-opus-4-6-v1", "Claude Opus 4.6 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-opus-4-6-v1", "Claude Opus 4.6 (US)", "amazon-bedrock"),
        ("anthropic.claude-opus-4-7", "Claude Opus 4.7", "amazon-bedrock"),
        ("eu.anthropic.claude-opus-4-7", "Claude Opus 4.7 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-opus-4-7", "Claude Opus 4.7 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-opus-4-7", "Claude Opus 4.7 (US)", "amazon-bedrock"),
        ("anthropic.claude-3-5-sonnet-20240620-v1:0", "Claude Sonnet 3.5", "amazon-bedrock"),
        ("anthropic.claude-3-5-sonnet-20241022-v2:0", "Claude Sonnet 3.5 v2", "amazon-bedrock"),
        ("anthropic.claude-3-7-sonnet-20250219-v1:0", "Claude Sonnet 3.7", "amazon-bedrock"),
        ("anthropic.claude-sonnet-4-20250514-v1:0", "Claude Sonnet 4", "amazon-bedrock"),
        ("eu.anthropic.claude-sonnet-4-20250514-v1:0", "Claude Sonnet 4 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-sonnet-4-20250514-v1:0", "Claude Sonnet 4 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-sonnet-4-20250514-v1:0", "Claude Sonnet 4 (US)", "amazon-bedrock"),
        ("anthropic.claude-sonnet-4-5-20250929-v1:0", "Claude Sonnet 4.5", "amazon-bedrock"),
        ("eu.anthropic.claude-sonnet-4-5-20250929-v1:0", "Claude Sonnet 4.5 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-sonnet-4-5-20250929-v1:0", "Claude Sonnet 4.5 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-sonnet-4-5-20250929-v1:0", "Claude Sonnet 4.5 (US)", "amazon-bedrock"),
        ("anthropic.claude-sonnet-4-6", "Claude Sonnet 4.6", "amazon-bedrock"),
        ("eu.anthropic.claude-sonnet-4-6", "Claude Sonnet 4.6 (EU)", "amazon-bedrock"),
        ("global.anthropic.claude-sonnet-4-6", "Claude Sonnet 4.6 (Global)", "amazon-bedrock"),
        ("us.anthropic.claude-sonnet-4-6", "Claude Sonnet 4.6 (US)", "amazon-bedrock"),
        ("deepseek.r1-v1:0", "DeepSeek-R1", "amazon-bedrock"),
        ("deepseek.v3-v1:0", "DeepSeek-V3.1", "amazon-bedrock"),
        ("deepseek.v3.2", "DeepSeek-V3.2", "amazon-bedrock"),
        ("mistral.devstral-2-123b", "Devstral 2 123B", "amazon-bedrock"),
        ("google.gemma-3-4b-it", "Gemma 3 4B IT", "amazon-bedrock"),
        ("zai.glm-4.7", "GLM-4.7", "amazon-bedrock"),
        ("zai.glm-4.7-flash", "GLM-4.7-Flash", "amazon-bedrock"),
        ("zai.glm-5", "GLM-5", "amazon-bedrock"),
        ("google.gemma-3-27b-it", "Google Gemma 3 27B Instruct", "amazon-bedrock"),
        ("openai.gpt-oss-safeguard-120b", "GPT OSS Safeguard 120B", "amazon-bedrock"),
        ("openai.gpt-oss-safeguard-20b", "GPT OSS Safeguard 20B", "amazon-bedrock"),
        ("openai.gpt-oss-120b-1:0", "gpt-oss-120b", "amazon-bedrock"),
        ("openai.gpt-oss-20b-1:0", "gpt-oss-20b", "amazon-bedrock"),
        ("moonshot.kimi-k2-thinking", "Kimi K2 Thinking", "amazon-bedrock"),
        ("moonshotai.kimi-k2.5", "Kimi K2.5", "amazon-bedrock"),
        ("meta.llama3-1-405b-instruct-v1:0", "Llama 3.1 405B Instruct", "amazon-bedrock"),
        ("meta.llama3-1-70b-instruct-v1:0", "Llama 3.1 70B Instruct", "amazon-bedrock"),
        ("meta.llama3-1-8b-instruct-v1:0", "Llama 3.1 8B Instruct", "amazon-bedrock"),
        ("meta.llama3-2-11b-instruct-v1:0", "Llama 3.2 11B Instruct", "amazon-bedrock"),
        ("meta.llama3-2-1b-instruct-v1:0", "Llama 3.2 1B Instruct", "amazon-bedrock"),
        ("meta.llama3-2-3b-instruct-v1:0", "Llama 3.2 3B Instruct", "amazon-bedrock"),
        ("meta.llama3-2-90b-instruct-v1:0", "Llama 3.2 90B Instruct", "amazon-bedrock"),
        ("meta.llama3-3-70b-instruct-v1:0", "Llama 3.3 70B Instruct", "amazon-bedrock"),
        ("meta.llama4-maverick-17b-instruct-v1:0", "Llama 4 Maverick 17B Instruct", "amazon-bedrock"),
        ("meta.llama4-scout-17b-instruct-v1:0", "Llama 4 Scout 17B Instruct", "amazon-bedrock"),
        ("mistral.magistral-small-2509", "Magistral Small 1.2", "amazon-bedrock"),
        ("minimax.minimax-m2", "MiniMax M2", "amazon-bedrock"),
        ("minimax.minimax-m2.1", "MiniMax M2.1", "amazon-bedrock"),
        ("minimax.minimax-m2.5", "MiniMax M2.5", "amazon-bedrock"),
        ("mistral.ministral-3-14b-instruct", "Ministral 14B 3.0", "amazon-bedrock"),
        ("mistral.ministral-3-3b-instruct", "Ministral 3 3B", "amazon-bedrock"),
        ("mistral.ministral-3-8b-instruct", "Ministral 3 8B", "amazon-bedrock"),
        ("mistral.mistral-large-3-675b-instruct", "Mistral Large 3", "amazon-bedrock"),
        ("amazon.nova-2-lite-v1:0", "Nova 2 Lite", "amazon-bedrock"),
        ("amazon.nova-lite-v1:0", "Nova Lite", "amazon-bedrock"),
        ("amazon.nova-micro-v1:0", "Nova Micro", "amazon-bedrock"),
        ("amazon.nova-premier-v1:0", "Nova Premier", "amazon-bedrock"),
        ("amazon.nova-pro-v1:0", "Nova Pro", "amazon-bedrock"),
        ("nvidia.nemotron-super-3-120b", "NVIDIA Nemotron 3 Super 120B A12B", "amazon-bedrock"),
        ("nvidia.nemotron-nano-12b-v2", "NVIDIA Nemotron Nano 12B v2 VL BF16", "amazon-bedrock"),
        ("nvidia.nemotron-nano-3-30b", "NVIDIA Nemotron Nano 3 30B", "amazon-bedrock"),
        ("nvidia.nemotron-nano-9b-v2", "NVIDIA Nemotron Nano 9B v2", "amazon-bedrock"),
        ("writer.palmyra-x4-v1:0", "Palmyra X4", "amazon-bedrock"),
        ("writer.palmyra-x5-v1:0", "Palmyra X5", "amazon-bedrock"),
        ("mistral.pixtral-large-2502-v1:0", "Pixtral Large (25.02)", "amazon-bedrock"),
        ("qwen.qwen3-next-80b-a3b", "Qwen/Qwen3-Next-80B-A3B-Instruct", "amazon-bedrock"),
        ("qwen.qwen3-vl-235b-a22b", "Qwen/Qwen3-VL-235B-A22B-Instruct", "amazon-bedrock"),
        ("qwen.qwen3-235b-a22b-2507-v1:0", "Qwen3 235B A22B 2507", "amazon-bedrock"),
        ("qwen.qwen3-32b-v1:0", "Qwen3 32B (dense)", "amazon-bedrock"),
        ("qwen.qwen3-coder-30b-a3b-v1:0", "Qwen3 Coder 30B A3B Instruct", "amazon-bedrock"),
        ("qwen.qwen3-coder-480b-a35b-v1:0", "Qwen3 Coder 480B A35B Instruct", "amazon-bedrock"),
        ("qwen.qwen3-coder-next", "Qwen3 Coder Next", "amazon-bedrock"),
        ("mistral.voxtral-mini-3b-2507", "Voxtral Mini 3B 2507", "amazon-bedrock"),
        ("mistral.voxtral-small-24b-2507", "Voxtral Small 24B 2507", "amazon-bedrock"),
        ("claude-3-haiku-20240307", "Claude Haiku 3", "anthropic"),
        ("claude-3-5-haiku-20241022", "Claude Haiku 3.5", "anthropic"),
        ("claude-3-5-haiku-latest", "Claude Haiku 3.5 (latest)", "anthropic"),
        ("claude-haiku-4-5-20251001", "Claude Haiku 4.5", "anthropic"),
        ("claude-haiku-4-5", "Claude Haiku 4.5 (latest)", "anthropic"),
        ("claude-3-opus-20240229", "Claude Opus 3", "anthropic"),
        ("claude-opus-4-20250514", "Claude Opus 4", "anthropic"),
        ("claude-opus-4-0", "Claude Opus 4 (latest)", "anthropic"),
        ("claude-opus-4-1-20250805", "Claude Opus 4.1", "anthropic"),
        ("claude-opus-4-1", "Claude Opus 4.1 (latest)", "anthropic"),
        ("claude-opus-4-5-20251101", "Claude Opus 4.5", "anthropic"),
        ("claude-opus-4-5", "Claude Opus 4.5 (latest)", "anthropic"),
        ("claude-opus-4-6", "Claude Opus 4.6", "anthropic"),
        ("claude-opus-4-7", "Claude Opus 4.7", "anthropic"),
        ("claude-3-sonnet-20240229", "Claude Sonnet 3", "anthropic"),
        ("claude-3-5-sonnet-20240620", "Claude Sonnet 3.5", "anthropic"),
        ("claude-3-5-sonnet-20241022", "Claude Sonnet 3.5 v2", "anthropic"),
        ("claude-3-7-sonnet-20250219", "Claude Sonnet 3.7", "anthropic"),
        ("claude-sonnet-4-20250514", "Claude Sonnet 4", "anthropic"),
        ("claude-sonnet-4-0", "Claude Sonnet 4 (latest)", "anthropic"),
        ("claude-sonnet-4-5-20250929", "Claude Sonnet 4.5", "anthropic"),
        ("claude-sonnet-4-5", "Claude Sonnet 4.5 (latest)", "anthropic"),
        ("claude-sonnet-4-6", "Claude Sonnet 4.6", "anthropic"),
        ("gpt-4", "GPT-4", "azure-openai-responses"),
        ("gpt-4-turbo", "GPT-4 Turbo", "azure-openai-responses"),
        ("gpt-4.1", "GPT-4.1", "azure-openai-responses"),
        ("gpt-4.1-mini", "GPT-4.1 mini", "azure-openai-responses"),
        ("gpt-4.1-nano", "GPT-4.1 nano", "azure-openai-responses"),
        ("gpt-4o", "GPT-4o", "azure-openai-responses"),
        ("gpt-4o-2024-05-13", "GPT-4o (2024-05-13)", "azure-openai-responses"),
        ("gpt-4o-2024-08-06", "GPT-4o (2024-08-06)", "azure-openai-responses"),
        ("gpt-4o-2024-11-20", "GPT-4o (2024-11-20)", "azure-openai-responses"),
        ("gpt-4o-mini", "GPT-4o mini", "azure-openai-responses"),
        ("gpt-5", "GPT-5", "azure-openai-responses"),
        ("gpt-5-chat-latest", "GPT-5 Chat Latest", "azure-openai-responses"),
        ("gpt-5-mini", "GPT-5 Mini", "azure-openai-responses"),
        ("gpt-5-nano", "GPT-5 Nano", "azure-openai-responses"),
        ("gpt-5-pro", "GPT-5 Pro", "azure-openai-responses"),
        ("gpt-5-codex", "GPT-5-Codex", "azure-openai-responses"),
        ("gpt-5.1", "GPT-5.1", "azure-openai-responses"),
        ("gpt-5.1-chat-latest", "GPT-5.1 Chat", "azure-openai-responses"),
        ("gpt-5.1-codex", "GPT-5.1 Codex", "azure-openai-responses"),
        ("gpt-5.1-codex-max", "GPT-5.1 Codex Max", "azure-openai-responses"),
        ("gpt-5.1-codex-mini", "GPT-5.1 Codex mini", "azure-openai-responses"),
        ("gpt-5.2", "GPT-5.2", "azure-openai-responses"),
        ("gpt-5.2-chat-latest", "GPT-5.2 Chat", "azure-openai-responses"),
        ("gpt-5.2-codex", "GPT-5.2 Codex", "azure-openai-responses"),
        ("gpt-5.2-pro", "GPT-5.2 Pro", "azure-openai-responses"),
        ("gpt-5.3-chat-latest", "GPT-5.3 Chat (latest)", "azure-openai-responses"),
        ("gpt-5.3-codex", "GPT-5.3 Codex", "azure-openai-responses"),
        ("gpt-5.3-codex-spark", "GPT-5.3 Codex Spark", "azure-openai-responses"),
        ("gpt-5.4", "GPT-5.4", "azure-openai-responses"),
        ("gpt-5.4-mini", "GPT-5.4 mini", "azure-openai-responses"),
        ("gpt-5.4-nano", "GPT-5.4 nano", "azure-openai-responses"),
        ("gpt-5.4-pro", "GPT-5.4 Pro", "azure-openai-responses"),
        ("gpt-5.5", "GPT-5.5", "azure-openai-responses"),
        ("gpt-5.5-pro", "GPT-5.5 Pro", "azure-openai-responses"),
        ("o1", "o1", "azure-openai-responses"),
        ("o1-pro", "o1-pro", "azure-openai-responses"),
        ("o3", "o3", "azure-openai-responses"),
        ("o3-deep-research", "o3-deep-research", "azure-openai-responses"),
        ("o3-mini", "o3-mini", "azure-openai-responses"),
        ("o3-pro", "o3-pro", "azure-openai-responses"),
        ("o4-mini", "o4-mini", "azure-openai-responses"),
        ("o4-mini-deep-research", "o4-mini-deep-research", "azure-openai-responses"),
        ("gpt-oss-120b", "GPT OSS 120B", "cerebras"),
        ("llama3.1-8b", "Llama 3.1 8B", "cerebras"),
        ("qwen-3-235b-a22b-instruct-2507", "Qwen 3 235B Instruct", "cerebras"),
        ("zai-glm-4.7", "Z.AI GLM-4.7", "cerebras"),
        ("@cf/google/gemma-4-26b-a4b-it", "Gemma 4 26B A4B IT", "cloudflare-workers-ai"),
        ("@cf/zai-org/glm-4.7-flash", "GLM-4.7-Flash", "cloudflare-workers-ai"),
        ("@cf/openai/gpt-oss-120b", "GPT OSS 120B", "cloudflare-workers-ai"),
        ("@cf/openai/gpt-oss-20b", "GPT OSS 20B", "cloudflare-workers-ai"),
        ("@cf/moonshotai/kimi-k2.5", "Kimi K2.5", "cloudflare-workers-ai"),
        ("@cf/moonshotai/kimi-k2.6", "Kimi K2.6", "cloudflare-workers-ai"),
        ("@cf/meta/llama-4-scout-17b-16e-instruct", "Llama 4 Scout 17B 16E Instruct", "cloudflare-workers-ai"),
        ("@cf/nvidia/nemotron-3-120b-a12b", "Nemotron 3 Super 120B", "cloudflare-workers-ai"),
        ("deepseek-v4-flash", "DeepSeek V4 Flash", "deepseek"),
        ("deepseek-v4-pro", "DeepSeek V4 Pro", "deepseek"),
        ("accounts/fireworks/models/deepseek-v3p1", "DeepSeek V3.1", "fireworks"),
        ("accounts/fireworks/models/deepseek-v3p2", "DeepSeek V3.2", "fireworks"),
        ("accounts/fireworks/models/deepseek-v4-pro", "DeepSeek V4 Pro", "fireworks"),
        ("accounts/fireworks/models/glm-4p5", "GLM 4.5", "fireworks"),
        ("accounts/fireworks/models/glm-4p5-air", "GLM 4.5 Air", "fireworks"),
        ("accounts/fireworks/models/glm-4p7", "GLM 4.7", "fireworks"),
        ("accounts/fireworks/models/glm-5", "GLM 5", "fireworks"),
        ("accounts/fireworks/models/glm-5p1", "GLM 5.1", "fireworks"),
        ("accounts/fireworks/models/gpt-oss-120b", "GPT OSS 120B", "fireworks"),
        ("accounts/fireworks/models/gpt-oss-20b", "GPT OSS 20B", "fireworks"),
        ("accounts/fireworks/models/kimi-k2-instruct", "Kimi K2 Instruct", "fireworks"),
        ("accounts/fireworks/models/kimi-k2-thinking", "Kimi K2 Thinking", "fireworks"),
        ("accounts/fireworks/models/kimi-k2p5", "Kimi K2.5", "fireworks"),
        ("accounts/fireworks/routers/kimi-k2p5-turbo", "Kimi K2.5 Turbo (firepass)", "fireworks"),
        ("accounts/fireworks/models/kimi-k2p6", "Kimi K2.6", "fireworks"),
        ("accounts/fireworks/models/minimax-m2p1", "MiniMax-M2.1", "fireworks"),
        ("accounts/fireworks/models/minimax-m2p5", "MiniMax-M2.5", "fireworks"),
        ("accounts/fireworks/models/minimax-m2p7", "MiniMax-M2.7", "fireworks"),
        ("accounts/fireworks/models/qwen3p6-plus", "Qwen 3.6 Plus", "fireworks"),
        ("claude-haiku-4.5", "Claude Haiku 4.5", "github-copilot"),
        ("claude-opus-4.5", "Claude Opus 4.5", "github-copilot"),
        ("claude-opus-4.6", "Claude Opus 4.6", "github-copilot"),
        ("claude-opus-4.7", "Claude Opus 4.7", "github-copilot"),
        ("claude-sonnet-4", "Claude Sonnet 4", "github-copilot"),
        ("claude-sonnet-4.5", "Claude Sonnet 4.5", "github-copilot"),
        ("claude-sonnet-4.6", "Claude Sonnet 4.6", "github-copilot"),
        ("gemini-2.5-pro", "Gemini 2.5 Pro", "github-copilot"),
        ("gemini-3-flash-preview", "Gemini 3 Flash", "github-copilot"),
        ("gemini-3-pro-preview", "Gemini 3 Pro Preview", "github-copilot"),
        ("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", "github-copilot"),
        ("gpt-4.1", "GPT-4.1", "github-copilot"),
        ("gpt-4o", "GPT-4o", "github-copilot"),
        ("gpt-5", "GPT-5", "github-copilot"),
        ("gpt-5-mini", "GPT-5-mini", "github-copilot"),
        ("gpt-5.1", "GPT-5.1", "github-copilot"),
        ("gpt-5.1-codex", "GPT-5.1-Codex", "github-copilot"),
        ("gpt-5.1-codex-max", "GPT-5.1-Codex-max", "github-copilot"),
        ("gpt-5.1-codex-mini", "GPT-5.1-Codex-mini", "github-copilot"),
        ("gpt-5.2", "GPT-5.2", "github-copilot"),
        ("gpt-5.2-codex", "GPT-5.2-Codex", "github-copilot"),
        ("gpt-5.3-codex", "GPT-5.3-Codex", "github-copilot"),
        ("gpt-5.4", "GPT-5.4", "github-copilot"),
        ("gpt-5.4-mini", "GPT-5.4 Mini", "github-copilot"),
        ("gpt-5.5", "GPT-5.5", "github-copilot"),
        ("grok-code-fast-1", "Grok Code Fast 1", "github-copilot"),
        ("gemini-1.5-flash", "Gemini 1.5 Flash", "google"),
        ("gemini-1.5-flash-8b", "Gemini 1.5 Flash-8B", "google"),
        ("gemini-1.5-pro", "Gemini 1.5 Pro", "google"),
        ("gemini-2.0-flash", "Gemini 2.0 Flash", "google"),
        ("gemini-2.0-flash-lite", "Gemini 2.0 Flash Lite", "google"),
        ("gemini-2.5-flash", "Gemini 2.5 Flash", "google"),
        ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite", "google"),
        ("gemini-2.5-flash-lite-preview-06-17", "Gemini 2.5 Flash Lite Preview 06-17", "google"),
        ("gemini-2.5-flash-lite-preview-09-2025", "Gemini 2.5 Flash Lite Preview 09-25", "google"),
        ("gemini-2.5-flash-preview-04-17", "Gemini 2.5 Flash Preview 04-17", "google"),
        ("gemini-2.5-flash-preview-05-20", "Gemini 2.5 Flash Preview 05-20", "google"),
        ("gemini-2.5-flash-preview-09-2025", "Gemini 2.5 Flash Preview 09-25", "google"),
        ("gemini-2.5-pro", "Gemini 2.5 Pro", "google"),
        ("gemini-2.5-pro-preview-05-06", "Gemini 2.5 Pro Preview 05-06", "google"),
        ("gemini-2.5-pro-preview-06-05", "Gemini 2.5 Pro Preview 06-05", "google"),
        ("gemini-3-flash-preview", "Gemini 3 Flash Preview", "google"),
        ("gemini-3-pro-preview", "Gemini 3 Pro Preview", "google"),
        ("gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview", "google"),
        ("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", "google"),
        ("gemini-3.1-pro-preview-customtools", "Gemini 3.1 Pro Preview Custom Tools", "google"),
        ("gemini-flash-latest", "Gemini Flash Latest", "google"),
        ("gemini-flash-lite-latest", "Gemini Flash-Lite Latest", "google"),
        ("gemini-live-2.5-flash", "Gemini Live 2.5 Flash", "google"),
        ("gemini-live-2.5-flash-preview-native-audio", "Gemini Live 2.5 Flash Preview Native Audio", "google"),
        ("gemma-3-27b-it", "Gemma 3 27B", "google"),
        ("gemma-4-26b-a4b-it", "Gemma 4 26B", "google"),
        ("gemma-4-31b-it", "Gemma 4 31B", "google"),
        ("claude-opus-4-5-thinking", "Claude Opus 4.5 Thinking (Antigravity)", "google-antigravity"),
        ("claude-opus-4-6-thinking", "Claude Opus 4.6 Thinking (Antigravity)", "google-antigravity"),
        ("claude-sonnet-4-5", "Claude Sonnet 4.5 (Antigravity)", "google-antigravity"),
        ("claude-sonnet-4-5-thinking", "Claude Sonnet 4.5 Thinking (Antigravity)", "google-antigravity"),
        ("claude-sonnet-4-6", "Claude Sonnet 4.6 (Antigravity)", "google-antigravity"),
        ("gemini-3-flash", "Gemini 3 Flash (Antigravity)", "google-antigravity"),
        ("gemini-3.1-pro-high", "Gemini 3.1 Pro High (Antigravity)", "google-antigravity"),
        ("gemini-3.1-pro-low", "Gemini 3.1 Pro Low (Antigravity)", "google-antigravity"),
        ("gpt-oss-120b-medium", "GPT-OSS 120B Medium (Antigravity)", "google-antigravity"),
        ("gemini-2.0-flash", "Gemini 2.0 Flash (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-2.5-flash", "Gemini 2.5 Flash (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-2.5-pro", "Gemini 2.5 Pro (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-3-flash-preview", "Gemini 3 Flash Preview (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-3-pro-preview", "Gemini 3 Pro Preview (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview (Cloud Code Assist)", "google-gemini-cli"),
        ("gemini-1.5-flash", "Gemini 1.5 Flash (Vertex)", "google-vertex"),
        ("gemini-1.5-flash-8b", "Gemini 1.5 Flash-8B (Vertex)", "google-vertex"),
        ("gemini-1.5-pro", "Gemini 1.5 Pro (Vertex)", "google-vertex"),
        ("gemini-2.0-flash", "Gemini 2.0 Flash (Vertex)", "google-vertex"),
        ("gemini-2.0-flash-lite", "Gemini 2.0 Flash Lite (Vertex)", "google-vertex"),
        ("gemini-2.5-flash", "Gemini 2.5 Flash (Vertex)", "google-vertex"),
        ("gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite (Vertex)", "google-vertex"),
        ("gemini-2.5-flash-lite-preview-09-2025", "Gemini 2.5 Flash Lite Preview 09-25 (Vertex)", "google-vertex"),
        ("gemini-2.5-pro", "Gemini 2.5 Pro (Vertex)", "google-vertex"),
        ("gemini-3-flash-preview", "Gemini 3 Flash Preview (Vertex)", "google-vertex"),
        ("gemini-3-pro-preview", "Gemini 3 Pro Preview (Vertex)", "google-vertex"),
        ("gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview (Vertex)", "google-vertex"),
        ("gemini-3.1-pro-preview-customtools", "Gemini 3.1 Pro Preview Custom Tools (Vertex)", "google-vertex"),
        ("groq/compound", "Compound", "groq"),
        ("groq/compound-mini", "Compound Mini", "groq"),
        ("deepseek-r1-distill-llama-70b", "DeepSeek R1 Distill Llama 70B", "groq"),
        ("gemma2-9b-it", "Gemma 2 9B", "groq"),
        ("openai/gpt-oss-120b", "GPT OSS 120B", "groq"),
        ("openai/gpt-oss-20b", "GPT OSS 20B", "groq"),
        ("moonshotai/kimi-k2-instruct", "Kimi K2 Instruct", "groq"),
        ("moonshotai/kimi-k2-instruct-0905", "Kimi K2 Instruct 0905", "groq"),
        ("llama3-70b-8192", "Llama 3 70B", "groq"),
        ("llama3-8b-8192", "Llama 3 8B", "groq"),
        ("llama-3.1-8b-instant", "Llama 3.1 8B Instant", "groq"),
        ("llama-3.3-70b-versatile", "Llama 3.3 70B Versatile", "groq"),
        ("meta-llama/llama-4-maverick-17b-128e-instruct", "Llama 4 Maverick 17B", "groq"),
        ("meta-llama/llama-4-scout-17b-16e-instruct", "Llama 4 Scout 17B", "groq"),
        ("mistral-saba-24b", "Mistral Saba 24B", "groq"),
        ("qwen-qwq-32b", "Qwen QwQ 32B", "groq"),
        ("qwen/qwen3-32b", "Qwen3 32B", "groq"),
        ("openai/gpt-oss-safeguard-20b", "Safety GPT OSS 20B", "groq"),
        ("deepseek-ai/DeepSeek-V4-Pro", "DeepSeek V4 Pro", "huggingface"),
        ("deepseek-ai/DeepSeek-R1-0528", "DeepSeek-R1-0528", "huggingface"),
        ("deepseek-ai/DeepSeek-V3.2", "DeepSeek-V3.2", "huggingface"),
        ("zai-org/GLM-4.7", "GLM-4.7", "huggingface"),
        ("zai-org/GLM-4.7-Flash", "GLM-4.7-Flash", "huggingface"),
        ("zai-org/GLM-5", "GLM-5", "huggingface"),
        ("zai-org/GLM-5.1", "GLM-5.1", "huggingface"),
        ("moonshotai/Kimi-K2-Instruct", "Kimi-K2-Instruct", "huggingface"),
        ("moonshotai/Kimi-K2-Instruct-0905", "Kimi-K2-Instruct-0905", "huggingface"),
        ("moonshotai/Kimi-K2-Thinking", "Kimi-K2-Thinking", "huggingface"),
        ("moonshotai/Kimi-K2.5", "Kimi-K2.5", "huggingface"),
        ("moonshotai/Kimi-K2.6", "Kimi-K2.6", "huggingface"),
        ("XiaomiMiMo/MiMo-V2-Flash", "MiMo-V2-Flash", "huggingface"),
        ("MiniMaxAI/MiniMax-M2.1", "MiniMax-M2.1", "huggingface"),
        ("MiniMaxAI/MiniMax-M2.5", "MiniMax-M2.5", "huggingface"),
        ("MiniMaxAI/MiniMax-M2.7", "MiniMax-M2.7", "huggingface"),
        ("Qwen/Qwen3-235B-A22B-Thinking-2507", "Qwen3-235B-A22B-Thinking-2507", "huggingface"),
        ("Qwen/Qwen3-Coder-480B-A35B-Instruct", "Qwen3-Coder-480B-A35B-Instruct", "huggingface"),
        ("Qwen/Qwen3-Coder-Next", "Qwen3-Coder-Next", "huggingface"),
        ("Qwen/Qwen3-Next-80B-A3B-Instruct", "Qwen3-Next-80B-A3B-Instruct", "huggingface"),
        ("Qwen/Qwen3-Next-80B-A3B-Thinking", "Qwen3-Next-80B-A3B-Thinking", "huggingface"),
        ("Qwen/Qwen3.5-397B-A17B", "Qwen3.5-397B-A17B", "huggingface"),
        ("kimi-for-coding", "Kimi For Coding", "kimi-coding"),
        ("kimi-k2-thinking", "Kimi K2 Thinking", "kimi-coding"),
        ("k2p6", "Kimi K2.6", "kimi-coding"),
        ("MiniMax-M2.7", "MiniMax-M2.7", "minimax"),
        ("MiniMax-M2.7-highspeed", "MiniMax-M2.7-highspeed", "minimax"),
        ("MiniMax-M2.7", "MiniMax-M2.7", "minimax-cn"),
        ("MiniMax-M2.7-highspeed", "MiniMax-M2.7-highspeed", "minimax-cn"),
        ("codestral-latest", "Codestral (latest)", "mistral"),
        ("devstral-2512", "Devstral 2", "mistral"),
        ("devstral-medium-latest", "Devstral 2 (latest)", "mistral"),
        ("devstral-medium-2507", "Devstral Medium", "mistral"),
        ("devstral-small-2507", "Devstral Small", "mistral"),
        ("labs-devstral-small-2512", "Devstral Small 2", "mistral"),
        ("devstral-small-2505", "Devstral Small 2505", "mistral"),
        ("magistral-medium-latest", "Magistral Medium (latest)", "mistral"),
        ("magistral-small", "Magistral Small", "mistral"),
        ("ministral-3b-latest", "Ministral 3B (latest)", "mistral"),
        ("ministral-8b-latest", "Ministral 8B (latest)", "mistral"),
        ("open-mistral-7b", "Mistral 7B", "mistral"),
        ("mistral-large-latest", "Mistral Large (latest)", "mistral"),
        ("mistral-large-2411", "Mistral Large 2.1", "mistral"),
        ("mistral-large-2512", "Mistral Large 3", "mistral"),
        ("mistral-medium-latest", "Mistral Medium (latest)", "mistral"),
        ("mistral-medium-2505", "Mistral Medium 3", "mistral"),
        ("mistral-medium-2508", "Mistral Medium 3.1", "mistral"),
        ("mistral-nemo", "Mistral Nemo", "mistral"),
        ("mistral-small-latest", "Mistral Small (latest)", "mistral"),
        ("mistral-small-2506", "Mistral Small 3.2", "mistral"),
        ("mistral-small-2603", "Mistral Small 4", "mistral"),
        ("open-mixtral-8x22b", "Mixtral 8x22B", "mistral"),
        ("open-mixtral-8x7b", "Mixtral 8x7B", "mistral"),
        ("pixtral-12b", "Pixtral 12B", "mistral"),
        ("pixtral-large-latest", "Pixtral Large (latest)", "mistral"),
        ("gpt-4", "GPT-4", "openai"),
        ("gpt-4-turbo", "GPT-4 Turbo", "openai"),
        ("gpt-4.1", "GPT-4.1", "openai"),
        ("gpt-4.1-mini", "GPT-4.1 mini", "openai"),
        ("gpt-4.1-nano", "GPT-4.1 nano", "openai"),
        ("gpt-4o", "GPT-4o", "openai"),
        ("gpt-4o-2024-05-13", "GPT-4o (2024-05-13)", "openai"),
        ("gpt-4o-2024-08-06", "GPT-4o (2024-08-06)", "openai"),
        ("gpt-4o-2024-11-20", "GPT-4o (2024-11-20)", "openai"),
        ("gpt-4o-mini", "GPT-4o mini", "openai"),
        ("gpt-5", "GPT-5", "openai"),
        ("gpt-5-chat-latest", "GPT-5 Chat Latest", "openai"),
        ("gpt-5-mini", "GPT-5 Mini", "openai"),
        ("gpt-5-nano", "GPT-5 Nano", "openai"),
        ("gpt-5-pro", "GPT-5 Pro", "openai"),
        ("gpt-5-codex", "GPT-5-Codex", "openai"),
        ("gpt-5.1", "GPT-5.1", "openai"),
        ("gpt-5.1-chat-latest", "GPT-5.1 Chat", "openai"),
        ("gpt-5.1-codex", "GPT-5.1 Codex", "openai"),
        ("gpt-5.1-codex-max", "GPT-5.1 Codex Max", "openai"),
        ("gpt-5.1-codex-mini", "GPT-5.1 Codex mini", "openai"),
        ("gpt-5.2", "GPT-5.2", "openai"),
        ("gpt-5.2-chat-latest", "GPT-5.2 Chat", "openai"),
        ("gpt-5.2-codex", "GPT-5.2 Codex", "openai"),
        ("gpt-5.2-pro", "GPT-5.2 Pro", "openai"),
        ("gpt-5.3-chat-latest", "GPT-5.3 Chat (latest)", "openai"),
        ("gpt-5.3-codex", "GPT-5.3 Codex", "openai"),
        ("gpt-5.3-codex-spark", "GPT-5.3 Codex Spark", "openai"),
        ("gpt-5.4", "GPT-5.4", "openai"),
        ("gpt-5.4-mini", "GPT-5.4 mini", "openai"),
        ("gpt-5.4-nano", "GPT-5.4 nano", "openai"),
        ("gpt-5.4-pro", "GPT-5.4 Pro", "openai"),
        ("gpt-5.5", "GPT-5.5", "openai"),
        ("gpt-5.5-pro", "GPT-5.5 Pro", "openai"),
        ("o1", "o1", "openai"),
        ("o1-pro", "o1-pro", "openai"),
        ("o3", "o3", "openai"),
        ("o3-deep-research", "o3-deep-research", "openai"),
        ("o3-mini", "o3-mini", "openai"),
        ("o3-pro", "o3-pro", "openai"),
        ("o4-mini", "o4-mini", "openai"),
        ("o4-mini-deep-research", "o4-mini-deep-research", "openai"),
        ("gpt-5.1", "GPT-5.1", "openai-codex"),
        ("gpt-5.1-codex-max", "GPT-5.1 Codex Max", "openai-codex"),
        ("gpt-5.1-codex-mini", "GPT-5.1 Codex Mini", "openai-codex"),
        ("gpt-5.2", "GPT-5.2", "openai-codex"),
        ("gpt-5.2-codex", "GPT-5.2 Codex", "openai-codex"),
        ("gpt-5.3-codex", "GPT-5.3 Codex", "openai-codex"),
        ("gpt-5.3-codex-spark", "GPT-5.3 Codex Spark", "openai-codex"),
        ("gpt-5.4", "GPT-5.4", "openai-codex"),
        ("gpt-5.4-mini", "GPT-5.4 Mini", "openai-codex"),
        ("gpt-5.5", "GPT-5.5", "openai-codex"),
        ("big-pickle", "Big Pickle", "opencode"),
        ("claude-haiku-4-5", "Claude Haiku 4.5", "opencode"),
        ("claude-opus-4-1", "Claude Opus 4.1", "opencode"),
        ("claude-opus-4-5", "Claude Opus 4.5", "opencode"),
        ("claude-opus-4-6", "Claude Opus 4.6", "opencode"),
        ("claude-opus-4-7", "Claude Opus 4.7", "opencode"),
        ("claude-sonnet-4", "Claude Sonnet 4", "opencode"),
        ("claude-sonnet-4-5", "Claude Sonnet 4.5", "opencode"),
        ("claude-sonnet-4-6", "Claude Sonnet 4.6", "opencode"),
        ("gemini-3-flash", "Gemini 3 Flash", "opencode"),
        ("gemini-3.1-pro", "Gemini 3.1 Pro Preview", "opencode"),
        ("glm-5", "GLM-5", "opencode"),
        ("glm-5.1", "GLM-5.1", "opencode"),
        ("gpt-5", "GPT-5", "opencode"),
        ("gpt-5-codex", "GPT-5 Codex", "opencode"),
        ("gpt-5-nano", "GPT-5 Nano", "opencode"),
        ("gpt-5.1", "GPT-5.1", "opencode"),
        ("gpt-5.1-codex", "GPT-5.1 Codex", "opencode"),
        ("gpt-5.1-codex-max", "GPT-5.1 Codex Max", "opencode"),
        ("gpt-5.1-codex-mini", "GPT-5.1 Codex Mini", "opencode"),
        ("gpt-5.2", "GPT-5.2", "opencode"),
        ("gpt-5.2-codex", "GPT-5.2 Codex", "opencode"),
        ("gpt-5.3-codex", "GPT-5.3 Codex", "opencode"),
        ("gpt-5.4", "GPT-5.4", "opencode"),
        ("gpt-5.4-mini", "GPT-5.4 Mini", "opencode"),
        ("gpt-5.4-nano", "GPT-5.4 Nano", "opencode"),
        ("gpt-5.4-pro", "GPT-5.4 Pro", "opencode"),
        ("gpt-5.5", "GPT-5.5", "opencode"),
        ("gpt-5.5-pro", "GPT-5.5 Pro", "opencode"),
        ("hy3-preview-free", "Hy3 preview Free", "opencode"),
        ("kimi-k2.5", "Kimi K2.5", "opencode"),
        ("kimi-k2.6", "Kimi K2.6", "opencode"),
        ("minimax-m2.5", "MiniMax M2.5", "opencode"),
        ("minimax-m2.5-free", "MiniMax M2.5 Free", "opencode"),
        ("minimax-m2.7", "MiniMax M2.7", "opencode"),
        ("nemotron-3-super-free", "Nemotron 3 Super Free", "opencode"),
        ("qwen3.5-plus", "Qwen3.5 Plus", "opencode"),
        ("qwen3.6-plus", "Qwen3.6 Plus", "opencode"),
        ("deepseek-v4-flash", "DeepSeek V4 Flash", "opencode-go"),
        ("deepseek-v4-pro", "DeepSeek V4 Pro", "opencode-go"),
        ("glm-5", "GLM-5", "opencode-go"),
        ("glm-5.1", "GLM-5.1", "opencode-go"),
        ("kimi-k2.5", "Kimi K2.5", "opencode-go"),
        ("kimi-k2.6", "Kimi K2.6 (3x limits)", "opencode-go"),
        ("mimo-v2-omni", "MiMo V2 Omni", "opencode-go"),
        ("mimo-v2-pro", "MiMo V2 Pro", "opencode-go"),
        ("mimo-v2.5", "MiMo V2.5", "opencode-go"),
        ("mimo-v2.5-pro", "MiMo V2.5 Pro", "opencode-go"),
        ("minimax-m2.5", "MiniMax M2.5", "opencode-go"),
        ("minimax-m2.7", "MiniMax M2.7", "opencode-go"),
        ("qwen3.5-plus", "Qwen3.5 Plus", "opencode-go"),
        ("qwen3.6-plus", "Qwen3.6 Plus", "opencode-go"),
        ("ai21/jamba-large-1.7", "AI21: Jamba Large 1.7", "openrouter"),
        ("allenai/olmo-3.1-32b-instruct", "AllenAI: Olmo 3.1 32B Instruct", "openrouter"),
        ("amazon/nova-2-lite-v1", "Amazon: Nova 2 Lite", "openrouter"),
        ("amazon/nova-lite-v1", "Amazon: Nova Lite 1.0", "openrouter"),
        ("amazon/nova-micro-v1", "Amazon: Nova Micro 1.0", "openrouter"),
        ("amazon/nova-premier-v1", "Amazon: Nova Premier 1.0", "openrouter"),
        ("amazon/nova-pro-v1", "Amazon: Nova Pro 1.0", "openrouter"),
        ("~anthropic/claude-haiku-latest", "Anthropic Claude Haiku Latest", "openrouter"),
        ("~anthropic/claude-sonnet-latest", "Anthropic Claude Sonnet Latest", "openrouter"),
        ("anthropic/claude-3-haiku", "Anthropic: Claude 3 Haiku", "openrouter"),
        ("anthropic/claude-3.5-haiku", "Anthropic: Claude 3.5 Haiku", "openrouter"),
        ("anthropic/claude-3.7-sonnet", "Anthropic: Claude 3.7 Sonnet", "openrouter"),
        ("anthropic/claude-3.7-sonnet:thinking", "Anthropic: Claude 3.7 Sonnet (thinking)", "openrouter"),
        ("anthropic/claude-haiku-4.5", "Anthropic: Claude Haiku 4.5", "openrouter"),
        ("anthropic/claude-opus-4", "Anthropic: Claude Opus 4", "openrouter"),
        ("anthropic/claude-opus-4.1", "Anthropic: Claude Opus 4.1", "openrouter"),
        ("anthropic/claude-opus-4.5", "Anthropic: Claude Opus 4.5", "openrouter"),
        ("anthropic/claude-opus-4.6", "Anthropic: Claude Opus 4.6", "openrouter"),
        ("anthropic/claude-opus-4.6-fast", "Anthropic: Claude Opus 4.6 (Fast)", "openrouter"),
        ("anthropic/claude-opus-4.7", "Anthropic: Claude Opus 4.7", "openrouter"),
        ("~anthropic/claude-opus-latest", "Anthropic: Claude Opus Latest", "openrouter"),
        ("anthropic/claude-sonnet-4", "Anthropic: Claude Sonnet 4", "openrouter"),
        ("anthropic/claude-sonnet-4.5", "Anthropic: Claude Sonnet 4.5", "openrouter"),
        ("anthropic/claude-sonnet-4.6", "Anthropic: Claude Sonnet 4.6", "openrouter"),
        ("arcee-ai/trinity-large-preview", "Arcee AI: Trinity Large Preview", "openrouter"),
        ("arcee-ai/trinity-large-thinking", "Arcee AI: Trinity Large Thinking", "openrouter"),
        ("arcee-ai/trinity-mini", "Arcee AI: Trinity Mini", "openrouter"),
        ("arcee-ai/virtuoso-large", "Arcee AI: Virtuoso Large", "openrouter"),
        ("auto", "Auto", "openrouter"),
        ("openrouter/auto", "Auto Router", "openrouter"),
        ("baidu/ernie-4.5-21b-a3b", "Baidu: ERNIE 4.5 21B A3B", "openrouter"),
        ("baidu/ernie-4.5-vl-28b-a3b", "Baidu: ERNIE 4.5 VL 28B A3B", "openrouter"),
        ("bytedance-seed/seed-1.6", "ByteDance Seed: Seed 1.6", "openrouter"),
        ("bytedance-seed/seed-1.6-flash", "ByteDance Seed: Seed 1.6 Flash", "openrouter"),
        ("bytedance-seed/seed-2.0-lite", "ByteDance Seed: Seed-2.0-Lite", "openrouter"),
        ("bytedance-seed/seed-2.0-mini", "ByteDance Seed: Seed-2.0-Mini", "openrouter"),
        ("cohere/command-r-08-2024", "Cohere: Command R (08-2024)", "openrouter"),
        ("cohere/command-r-plus-08-2024", "Cohere: Command R+ (08-2024)", "openrouter"),
        ("deepseek/deepseek-chat", "DeepSeek: DeepSeek V3", "openrouter"),
        ("deepseek/deepseek-chat-v3-0324", "DeepSeek: DeepSeek V3 0324", "openrouter"),
        ("deepseek/deepseek-chat-v3.1", "DeepSeek: DeepSeek V3.1", "openrouter"),
        ("deepseek/deepseek-v3.1-terminus", "DeepSeek: DeepSeek V3.1 Terminus", "openrouter"),
        ("deepseek/deepseek-v3.2", "DeepSeek: DeepSeek V3.2", "openrouter"),
        ("deepseek/deepseek-v3.2-exp", "DeepSeek: DeepSeek V3.2 Exp", "openrouter"),
        ("deepseek/deepseek-v4-flash", "DeepSeek: DeepSeek V4 Flash", "openrouter"),
        ("deepseek/deepseek-v4-pro", "DeepSeek: DeepSeek V4 Pro", "openrouter"),
        ("deepseek/deepseek-r1", "DeepSeek: R1", "openrouter"),
        ("deepseek/deepseek-r1-0528", "DeepSeek: R1 0528", "openrouter"),
        ("essentialai/rnj-1-instruct", "EssentialAI: Rnj 1 Instruct", "openrouter"),
        ("openrouter/free", "Free Models Router", "openrouter"),
        ("~google/gemini-flash-latest", "Google Gemini Flash Latest", "openrouter"),
        ("~google/gemini-pro-latest", "Google Gemini Pro Latest", "openrouter"),
        ("google/gemini-2.0-flash-001", "Google: Gemini 2.0 Flash", "openrouter"),
        ("google/gemini-2.0-flash-lite-001", "Google: Gemini 2.0 Flash Lite", "openrouter"),
        ("google/gemini-2.5-flash", "Google: Gemini 2.5 Flash", "openrouter"),
        ("google/gemini-2.5-flash-lite", "Google: Gemini 2.5 Flash Lite", "openrouter"),
        ("google/gemini-2.5-flash-lite-preview-09-2025", "Google: Gemini 2.5 Flash Lite Preview 09-2025", "openrouter"),
        ("google/gemini-2.5-pro", "Google: Gemini 2.5 Pro", "openrouter"),
        ("google/gemini-2.5-pro-preview-05-06", "Google: Gemini 2.5 Pro Preview 05-06", "openrouter"),
        ("google/gemini-2.5-pro-preview", "Google: Gemini 2.5 Pro Preview 06-05", "openrouter"),
        ("google/gemini-3-flash-preview", "Google: Gemini 3 Flash Preview", "openrouter"),
        ("google/gemini-3.1-flash-lite-preview", "Google: Gemini 3.1 Flash Lite Preview", "openrouter"),
        ("google/gemini-3.1-pro-preview", "Google: Gemini 3.1 Pro Preview", "openrouter"),
        ("google/gemini-3.1-pro-preview-customtools", "Google: Gemini 3.1 Pro Preview Custom Tools", "openrouter"),
        ("google/gemma-3-12b-it", "Google: Gemma 3 12B", "openrouter"),
        ("google/gemma-3-27b-it", "Google: Gemma 3 27B", "openrouter"),
        ("google/gemma-4-26b-a4b-it", "Google: Gemma 4 26B A4B ", "openrouter"),
        ("google/gemma-4-26b-a4b-it:free", "Google: Gemma 4 26B A4B  (free)", "openrouter"),
        ("google/gemma-4-31b-it", "Google: Gemma 4 31B", "openrouter"),
        ("google/gemma-4-31b-it:free", "Google: Gemma 4 31B (free)", "openrouter"),
        ("inception/mercury-2", "Inception: Mercury 2", "openrouter"),
        ("inclusionai/ling-2.6-1t:free", "inclusionAI: Ling-2.6-1T (free)", "openrouter"),
        ("inclusionai/ling-2.6-flash", "inclusionAI: Ling-2.6-flash", "openrouter"),
        ("kwaipilot/kat-coder-pro-v2", "Kwaipilot: KAT-Coder-Pro V2", "openrouter"),
        ("meta-llama/llama-3-8b-instruct", "Meta: Llama 3 8B Instruct", "openrouter"),
        ("meta-llama/llama-3.1-70b-instruct", "Meta: Llama 3.1 70B Instruct", "openrouter"),
        ("meta-llama/llama-3.1-8b-instruct", "Meta: Llama 3.1 8B Instruct", "openrouter"),
        ("meta-llama/llama-3.3-70b-instruct", "Meta: Llama 3.3 70B Instruct", "openrouter"),
        ("meta-llama/llama-3.3-70b-instruct:free", "Meta: Llama 3.3 70B Instruct (free)", "openrouter"),
        ("meta-llama/llama-4-scout", "Meta: Llama 4 Scout", "openrouter"),
        ("minimax/minimax-m1", "MiniMax: MiniMax M1", "openrouter"),
        ("minimax/minimax-m2", "MiniMax: MiniMax M2", "openrouter"),
        ("minimax/minimax-m2.1", "MiniMax: MiniMax M2.1", "openrouter"),
        ("minimax/minimax-m2.5", "MiniMax: MiniMax M2.5", "openrouter"),
        ("minimax/minimax-m2.5:free", "MiniMax: MiniMax M2.5 (free)", "openrouter"),
        ("minimax/minimax-m2.7", "MiniMax: MiniMax M2.7", "openrouter"),
        ("mistralai/mistral-large", "Mistral Large", "openrouter"),
        ("mistralai/mistral-large-2407", "Mistral Large 2407", "openrouter"),
        ("mistralai/mistral-large-2411", "Mistral Large 2411", "openrouter"),
        ("mistralai/codestral-2508", "Mistral: Codestral 2508", "openrouter"),
        ("mistralai/devstral-2512", "Mistral: Devstral 2 2512", "openrouter"),
        ("mistralai/devstral-medium", "Mistral: Devstral Medium", "openrouter"),
        ("mistralai/devstral-small", "Mistral: Devstral Small 1.1", "openrouter"),
        ("mistralai/ministral-14b-2512", "Mistral: Ministral 3 14B 2512", "openrouter"),
        ("mistralai/ministral-3b-2512", "Mistral: Ministral 3 3B 2512", "openrouter"),
        ("mistralai/ministral-8b-2512", "Mistral: Ministral 3 8B 2512", "openrouter"),
        ("mistralai/mistral-large-2512", "Mistral: Mistral Large 3 2512", "openrouter"),
        ("mistralai/mistral-medium-3", "Mistral: Mistral Medium 3", "openrouter"),
        ("mistralai/mistral-medium-3.1", "Mistral: Mistral Medium 3.1", "openrouter"),
        ("mistralai/mistral-nemo", "Mistral: Mistral Nemo", "openrouter"),
        ("mistralai/mistral-small-3.2-24b-instruct", "Mistral: Mistral Small 3.2 24B", "openrouter"),
        ("mistralai/mistral-small-2603", "Mistral: Mistral Small 4", "openrouter"),
        ("mistralai/mixtral-8x22b-instruct", "Mistral: Mixtral 8x22B Instruct", "openrouter"),
        ("mistralai/mixtral-8x7b-instruct", "Mistral: Mixtral 8x7B Instruct", "openrouter"),
        ("mistralai/pixtral-large-2411", "Mistral: Pixtral Large 2411", "openrouter"),
        ("mistralai/mistral-saba", "Mistral: Saba", "openrouter"),
        ("mistralai/voxtral-small-24b-2507", "Mistral: Voxtral Small 24B 2507", "openrouter"),
        ("~moonshotai/kimi-latest", "MoonshotAI Kimi Latest", "openrouter"),
        ("moonshotai/kimi-k2", "MoonshotAI: Kimi K2 0711", "openrouter"),
        ("moonshotai/kimi-k2-0905", "MoonshotAI: Kimi K2 0905", "openrouter"),
        ("moonshotai/kimi-k2-thinking", "MoonshotAI: Kimi K2 Thinking", "openrouter"),
        ("moonshotai/kimi-k2.5", "MoonshotAI: Kimi K2.5", "openrouter"),
        ("moonshotai/kimi-k2.6", "MoonshotAI: Kimi K2.6", "openrouter"),
        ("nex-agi/deepseek-v3.1-nex-n1", "Nex AGI: DeepSeek V3.1 Nex N1", "openrouter"),
        ("nvidia/llama-3.1-nemotron-70b-instruct", "NVIDIA: Llama 3.1 Nemotron 70B Instruct", "openrouter"),
        ("nvidia/llama-3.3-nemotron-super-49b-v1.5", "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5", "openrouter"),
        ("nvidia/nemotron-3-nano-30b-a3b", "NVIDIA: Nemotron 3 Nano 30B A3B", "openrouter"),
        ("nvidia/nemotron-3-nano-30b-a3b:free", "NVIDIA: Nemotron 3 Nano 30B A3B (free)", "openrouter"),
        ("nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", "NVIDIA: Nemotron 3 Nano Omni (free)", "openrouter"),
        ("nvidia/nemotron-3-super-120b-a12b", "NVIDIA: Nemotron 3 Super", "openrouter"),
        ("nvidia/nemotron-3-super-120b-a12b:free", "NVIDIA: Nemotron 3 Super (free)", "openrouter"),
        ("nvidia/nemotron-nano-12b-v2-vl:free", "NVIDIA: Nemotron Nano 12B 2 VL (free)", "openrouter"),
        ("nvidia/nemotron-nano-9b-v2", "NVIDIA: Nemotron Nano 9B V2", "openrouter"),
        ("nvidia/nemotron-nano-9b-v2:free", "NVIDIA: Nemotron Nano 9B V2 (free)", "openrouter"),
        ("~openai/gpt-latest", "OpenAI GPT Latest", "openrouter"),
        ("~openai/gpt-mini-latest", "OpenAI GPT Mini Latest", "openrouter"),
        ("openai/gpt-audio", "OpenAI: GPT Audio", "openrouter"),
        ("openai/gpt-audio-mini", "OpenAI: GPT Audio Mini", "openrouter"),
        ("openai/gpt-3.5-turbo", "OpenAI: GPT-3.5 Turbo", "openrouter"),
        ("openai/gpt-3.5-turbo-0613", "OpenAI: GPT-3.5 Turbo (older v0613)", "openrouter"),
        ("openai/gpt-3.5-turbo-16k", "OpenAI: GPT-3.5 Turbo 16k", "openrouter"),
        ("openai/gpt-4", "OpenAI: GPT-4", "openrouter"),
        ("openai/gpt-4-0314", "OpenAI: GPT-4 (older v0314)", "openrouter"),
        ("openai/gpt-4-turbo", "OpenAI: GPT-4 Turbo", "openrouter"),
        ("openai/gpt-4-1106-preview", "OpenAI: GPT-4 Turbo (older v1106)", "openrouter"),
        ("openai/gpt-4-turbo-preview", "OpenAI: GPT-4 Turbo Preview", "openrouter"),
        ("openai/gpt-4.1", "OpenAI: GPT-4.1", "openrouter"),
        ("openai/gpt-4.1-mini", "OpenAI: GPT-4.1 Mini", "openrouter"),
        ("openai/gpt-4.1-nano", "OpenAI: GPT-4.1 Nano", "openrouter"),
        ("openai/gpt-4o", "OpenAI: GPT-4o", "openrouter"),
        ("openai/gpt-4o-2024-05-13", "OpenAI: GPT-4o (2024-05-13)", "openrouter"),
        ("openai/gpt-4o-2024-08-06", "OpenAI: GPT-4o (2024-08-06)", "openrouter"),
        ("openai/gpt-4o-2024-11-20", "OpenAI: GPT-4o (2024-11-20)", "openrouter"),
        ("openai/gpt-4o-audio-preview", "OpenAI: GPT-4o Audio", "openrouter"),
        ("openai/gpt-4o-mini", "OpenAI: GPT-4o-mini", "openrouter"),
        ("openai/gpt-4o-mini-2024-07-18", "OpenAI: GPT-4o-mini (2024-07-18)", "openrouter"),
        ("openai/gpt-5", "OpenAI: GPT-5", "openrouter"),
        ("openai/gpt-5-codex", "OpenAI: GPT-5 Codex", "openrouter"),
        ("openai/gpt-5-mini", "OpenAI: GPT-5 Mini", "openrouter"),
        ("openai/gpt-5-nano", "OpenAI: GPT-5 Nano", "openrouter"),
        ("openai/gpt-5-pro", "OpenAI: GPT-5 Pro", "openrouter"),
        ("openai/gpt-5.1", "OpenAI: GPT-5.1", "openrouter"),
        ("openai/gpt-5.1-chat", "OpenAI: GPT-5.1 Chat", "openrouter"),
        ("openai/gpt-5.1-codex", "OpenAI: GPT-5.1-Codex", "openrouter"),
        ("openai/gpt-5.1-codex-max", "OpenAI: GPT-5.1-Codex-Max", "openrouter"),
        ("openai/gpt-5.1-codex-mini", "OpenAI: GPT-5.1-Codex-Mini", "openrouter"),
        ("openai/gpt-5.2", "OpenAI: GPT-5.2", "openrouter"),
        ("openai/gpt-5.2-chat", "OpenAI: GPT-5.2 Chat", "openrouter"),
        ("openai/gpt-5.2-pro", "OpenAI: GPT-5.2 Pro", "openrouter"),
        ("openai/gpt-5.2-codex", "OpenAI: GPT-5.2-Codex", "openrouter"),
        ("openai/gpt-5.3-chat", "OpenAI: GPT-5.3 Chat", "openrouter"),
        ("openai/gpt-5.3-codex", "OpenAI: GPT-5.3-Codex", "openrouter"),
        ("openai/gpt-5.4", "OpenAI: GPT-5.4", "openrouter"),
        ("openai/gpt-5.4-mini", "OpenAI: GPT-5.4 Mini", "openrouter"),
        ("openai/gpt-5.4-nano", "OpenAI: GPT-5.4 Nano", "openrouter"),
        ("openai/gpt-5.4-pro", "OpenAI: GPT-5.4 Pro", "openrouter"),
        ("openai/gpt-5.5", "OpenAI: GPT-5.5", "openrouter"),
        ("openai/gpt-5.5-pro", "OpenAI: GPT-5.5 Pro", "openrouter"),
        ("openai/gpt-oss-120b", "OpenAI: gpt-oss-120b", "openrouter"),
        ("openai/gpt-oss-120b:free", "OpenAI: gpt-oss-120b (free)", "openrouter"),
        ("openai/gpt-oss-20b", "OpenAI: gpt-oss-20b", "openrouter"),
        ("openai/gpt-oss-20b:free", "OpenAI: gpt-oss-20b (free)", "openrouter"),
        ("openai/gpt-oss-safeguard-20b", "OpenAI: gpt-oss-safeguard-20b", "openrouter"),
        ("openai/o1", "OpenAI: o1", "openrouter"),
        ("openai/o3", "OpenAI: o3", "openrouter"),
        ("openai/o3-deep-research", "OpenAI: o3 Deep Research", "openrouter"),
        ("openai/o3-mini", "OpenAI: o3 Mini", "openrouter"),
        ("openai/o3-mini-high", "OpenAI: o3 Mini High", "openrouter"),
        ("openai/o3-pro", "OpenAI: o3 Pro", "openrouter"),
        ("openai/o4-mini", "OpenAI: o4 Mini", "openrouter"),
        ("openai/o4-mini-deep-research", "OpenAI: o4 Mini Deep Research", "openrouter"),
        ("openai/o4-mini-high", "OpenAI: o4 Mini High", "openrouter"),
        ("poolside/laguna-m.1:free", "Poolside: Laguna M.1 (free)", "openrouter"),
        ("poolside/laguna-xs.2:free", "Poolside: Laguna XS.2 (free)", "openrouter"),
        ("prime-intellect/intellect-3", "Prime Intellect: INTELLECT-3", "openrouter"),
        ("qwen/qwen-plus-2025-07-28", "Qwen: Qwen Plus 0728", "openrouter"),
        ("qwen/qwen-plus-2025-07-28:thinking", "Qwen: Qwen Plus 0728 (thinking)", "openrouter"),
        ("qwen/qwen-vl-max", "Qwen: Qwen VL Max", "openrouter"),
        ("qwen/qwen-max", "Qwen: Qwen-Max ", "openrouter"),
        ("qwen/qwen-plus", "Qwen: Qwen-Plus", "openrouter"),
        ("qwen/qwen-turbo", "Qwen: Qwen-Turbo", "openrouter"),
        ("qwen/qwen-2.5-7b-instruct", "Qwen: Qwen2.5 7B Instruct", "openrouter"),
        ("qwen/qwen3-14b", "Qwen: Qwen3 14B", "openrouter"),
        ("qwen/qwen3-235b-a22b", "Qwen: Qwen3 235B A22B", "openrouter"),
        ("qwen/qwen3-235b-a22b-2507", "Qwen: Qwen3 235B A22B Instruct 2507", "openrouter"),
        ("qwen/qwen3-235b-a22b-thinking-2507", "Qwen: Qwen3 235B A22B Thinking 2507", "openrouter"),
        ("qwen/qwen3-30b-a3b", "Qwen: Qwen3 30B A3B", "openrouter"),
        ("qwen/qwen3-30b-a3b-instruct-2507", "Qwen: Qwen3 30B A3B Instruct 2507", "openrouter"),
        ("qwen/qwen3-30b-a3b-thinking-2507", "Qwen: Qwen3 30B A3B Thinking 2507", "openrouter"),
        ("qwen/qwen3-32b", "Qwen: Qwen3 32B", "openrouter"),
        ("qwen/qwen3-8b", "Qwen: Qwen3 8B", "openrouter"),
        ("qwen/qwen3-coder-30b-a3b-instruct", "Qwen: Qwen3 Coder 30B A3B Instruct", "openrouter"),
        ("qwen/qwen3-coder", "Qwen: Qwen3 Coder 480B A35B", "openrouter"),
        ("qwen/qwen3-coder:free", "Qwen: Qwen3 Coder 480B A35B (free)", "openrouter"),
        ("qwen/qwen3-coder-flash", "Qwen: Qwen3 Coder Flash", "openrouter"),
        ("qwen/qwen3-coder-next", "Qwen: Qwen3 Coder Next", "openrouter"),
        ("qwen/qwen3-coder-plus", "Qwen: Qwen3 Coder Plus", "openrouter"),
        ("qwen/qwen3-max", "Qwen: Qwen3 Max", "openrouter"),
        ("qwen/qwen3-max-thinking", "Qwen: Qwen3 Max Thinking", "openrouter"),
        ("qwen/qwen3-next-80b-a3b-instruct", "Qwen: Qwen3 Next 80B A3B Instruct", "openrouter"),
        ("qwen/qwen3-next-80b-a3b-instruct:free", "Qwen: Qwen3 Next 80B A3B Instruct (free)", "openrouter"),
        ("qwen/qwen3-next-80b-a3b-thinking", "Qwen: Qwen3 Next 80B A3B Thinking", "openrouter"),
        ("qwen/qwen3-vl-235b-a22b-instruct", "Qwen: Qwen3 VL 235B A22B Instruct", "openrouter"),
        ("qwen/qwen3-vl-235b-a22b-thinking", "Qwen: Qwen3 VL 235B A22B Thinking", "openrouter"),
        ("qwen/qwen3-vl-30b-a3b-instruct", "Qwen: Qwen3 VL 30B A3B Instruct", "openrouter"),
        ("qwen/qwen3-vl-30b-a3b-thinking", "Qwen: Qwen3 VL 30B A3B Thinking", "openrouter"),
        ("qwen/qwen3-vl-32b-instruct", "Qwen: Qwen3 VL 32B Instruct", "openrouter"),
        ("qwen/qwen3-vl-8b-instruct", "Qwen: Qwen3 VL 8B Instruct", "openrouter"),
        ("qwen/qwen3-vl-8b-thinking", "Qwen: Qwen3 VL 8B Thinking", "openrouter"),
        ("qwen/qwen3.5-397b-a17b", "Qwen: Qwen3.5 397B A17B", "openrouter"),
        ("qwen/qwen3.5-plus-02-15", "Qwen: Qwen3.5 Plus 2026-02-15", "openrouter"),
        ("qwen/qwen3.5-plus-20260420", "Qwen: Qwen3.5 Plus 2026-04-20", "openrouter"),
        ("qwen/qwen3.5-122b-a10b", "Qwen: Qwen3.5-122B-A10B", "openrouter"),
        ("qwen/qwen3.5-27b", "Qwen: Qwen3.5-27B", "openrouter"),
        ("qwen/qwen3.5-35b-a3b", "Qwen: Qwen3.5-35B-A3B", "openrouter"),
        ("qwen/qwen3.5-9b", "Qwen: Qwen3.5-9B", "openrouter"),
        ("qwen/qwen3.5-flash-02-23", "Qwen: Qwen3.5-Flash", "openrouter"),
        ("qwen/qwen3.6-27b", "Qwen: Qwen3.6 27B", "openrouter"),
        ("qwen/qwen3.6-flash", "Qwen: Qwen3.6 Flash", "openrouter"),
        ("qwen/qwen3.6-max-preview", "Qwen: Qwen3.6 Max Preview", "openrouter"),
        ("qwen/qwen3.6-plus", "Qwen: Qwen3.6 Plus", "openrouter"),
        ("qwen/qwen-2.5-72b-instruct", "Qwen2.5 72B Instruct", "openrouter"),
        ("rekaai/reka-edge", "Reka Edge", "openrouter"),
        ("relace/relace-search", "Relace: Relace Search", "openrouter"),
        ("sao10k/l3-euryale-70b", "Sao10k: Llama 3 Euryale 70B v2.1", "openrouter"),
        ("sao10k/l3.1-euryale-70b", "Sao10K: Llama 3.1 Euryale 70B v2.2", "openrouter"),
        ("stepfun/step-3.5-flash", "StepFun: Step 3.5 Flash", "openrouter"),
        ("tencent/hy3-preview:free", "Tencent: Hy3 preview (free)", "openrouter"),
        ("thedrummer/rocinante-12b", "TheDrummer: Rocinante 12B", "openrouter"),
        ("thedrummer/unslopnemo-12b", "TheDrummer: UnslopNemo 12B", "openrouter"),
        ("tngtech/deepseek-r1t2-chimera", "TNG: DeepSeek R1T2 Chimera", "openrouter"),
        ("alibaba/tongyi-deepresearch-30b-a3b", "Tongyi DeepResearch 30B A3B", "openrouter"),
        ("upstage/solar-pro-3", "Upstage: Solar Pro 3", "openrouter"),
        ("x-ai/grok-3", "xAI: Grok 3", "openrouter"),
        ("x-ai/grok-3-beta", "xAI: Grok 3 Beta", "openrouter"),
        ("x-ai/grok-3-mini", "xAI: Grok 3 Mini", "openrouter"),
        ("x-ai/grok-3-mini-beta", "xAI: Grok 3 Mini Beta", "openrouter"),
        ("x-ai/grok-4", "xAI: Grok 4", "openrouter"),
        ("x-ai/grok-4-fast", "xAI: Grok 4 Fast", "openrouter"),
        ("x-ai/grok-4.1-fast", "xAI: Grok 4.1 Fast", "openrouter"),
        ("x-ai/grok-4.20", "xAI: Grok 4.20", "openrouter"),
        ("x-ai/grok-code-fast-1", "xAI: Grok Code Fast 1", "openrouter"),
        ("xiaomi/mimo-v2-flash", "Xiaomi: MiMo-V2-Flash", "openrouter"),
        ("xiaomi/mimo-v2-omni", "Xiaomi: MiMo-V2-Omni", "openrouter"),
        ("xiaomi/mimo-v2-pro", "Xiaomi: MiMo-V2-Pro", "openrouter"),
        ("xiaomi/mimo-v2.5", "Xiaomi: MiMo-V2.5", "openrouter"),
        ("xiaomi/mimo-v2.5-pro", "Xiaomi: MiMo-V2.5-Pro", "openrouter"),
        ("z-ai/glm-4-32b", "Z.ai: GLM 4 32B ", "openrouter"),
        ("z-ai/glm-4.5", "Z.ai: GLM 4.5", "openrouter"),
        ("z-ai/glm-4.5-air", "Z.ai: GLM 4.5 Air", "openrouter"),
        ("z-ai/glm-4.5-air:free", "Z.ai: GLM 4.5 Air (free)", "openrouter"),
        ("z-ai/glm-4.5v", "Z.ai: GLM 4.5V", "openrouter"),
        ("z-ai/glm-4.6", "Z.ai: GLM 4.6", "openrouter"),
        ("z-ai/glm-4.6v", "Z.ai: GLM 4.6V", "openrouter"),
        ("z-ai/glm-4.7", "Z.ai: GLM 4.7", "openrouter"),
        ("z-ai/glm-4.7-flash", "Z.ai: GLM 4.7 Flash", "openrouter"),
        ("z-ai/glm-5", "Z.ai: GLM 5", "openrouter"),
        ("z-ai/glm-5-turbo", "Z.ai: GLM 5 Turbo", "openrouter"),
        ("z-ai/glm-5.1", "Z.ai: GLM 5.1", "openrouter"),
        ("z-ai/glm-5v-turbo", "Z.ai: GLM 5V Turbo", "openrouter"),
        ("anthropic/claude-3-haiku", "Claude 3 Haiku", "vercel-ai-gateway"),
        ("anthropic/claude-3.5-haiku", "Claude 3.5 Haiku", "vercel-ai-gateway"),
        ("anthropic/claude-3.7-sonnet", "Claude 3.7 Sonnet", "vercel-ai-gateway"),
        ("anthropic/claude-haiku-4.5", "Claude Haiku 4.5", "vercel-ai-gateway"),
        ("anthropic/claude-opus-4", "Claude Opus 4", "vercel-ai-gateway"),
        ("anthropic/claude-opus-4.1", "Claude Opus 4.1", "vercel-ai-gateway"),
        ("anthropic/claude-opus-4.5", "Claude Opus 4.5", "vercel-ai-gateway"),
        ("anthropic/claude-opus-4.6", "Claude Opus 4.6", "vercel-ai-gateway"),
        ("anthropic/claude-opus-4.7", "Claude Opus 4.7", "vercel-ai-gateway"),
        ("anthropic/claude-sonnet-4", "Claude Sonnet 4", "vercel-ai-gateway"),
        ("anthropic/claude-sonnet-4.5", "Claude Sonnet 4.5", "vercel-ai-gateway"),
        ("anthropic/claude-sonnet-4.6", "Claude Sonnet 4.6", "vercel-ai-gateway"),
        ("cohere/command-a", "Command A", "vercel-ai-gateway"),
        ("deepseek/deepseek-v3", "DeepSeek V3 0324", "vercel-ai-gateway"),
        ("deepseek/deepseek-v3.1-terminus", "DeepSeek V3.1 Terminus", "vercel-ai-gateway"),
        ("deepseek/deepseek-v3.2", "DeepSeek V3.2", "vercel-ai-gateway"),
        ("deepseek/deepseek-v3.2-thinking", "DeepSeek V3.2 Thinking", "vercel-ai-gateway"),
        ("deepseek/deepseek-v4-flash", "DeepSeek V4 Flash", "vercel-ai-gateway"),
        ("deepseek/deepseek-v4-pro", "DeepSeek V4 Pro", "vercel-ai-gateway"),
        ("deepseek/deepseek-r1", "DeepSeek-R1", "vercel-ai-gateway"),
        ("deepseek/deepseek-v3.1", "DeepSeek-V3.1", "vercel-ai-gateway"),
        ("mistral/devstral-2", "Devstral 2", "vercel-ai-gateway"),
        ("mistral/devstral-small", "Devstral Small 1.1", "vercel-ai-gateway"),
        ("mistral/devstral-small-2", "Devstral Small 2", "vercel-ai-gateway"),
        ("google/gemini-2.0-flash", "Gemini 2.0 Flash", "vercel-ai-gateway"),
        ("google/gemini-2.0-flash-lite", "Gemini 2.0 Flash Lite", "vercel-ai-gateway"),
        ("google/gemini-2.5-flash", "Gemini 2.5 Flash", "vercel-ai-gateway"),
        ("google/gemini-2.5-flash-lite", "Gemini 2.5 Flash Lite", "vercel-ai-gateway"),
        ("google/gemini-2.5-pro", "Gemini 2.5 Pro", "vercel-ai-gateway"),
        ("google/gemini-3-flash", "Gemini 3 Flash", "vercel-ai-gateway"),
        ("google/gemini-3-pro-preview", "Gemini 3 Pro Preview", "vercel-ai-gateway"),
        ("google/gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview", "vercel-ai-gateway"),
        ("google/gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview", "vercel-ai-gateway"),
        ("google/gemma-4-26b-a4b-it", "Gemma 4 26B A4B IT", "vercel-ai-gateway"),
        ("google/gemma-4-31b-it", "Gemma 4 31B IT", "vercel-ai-gateway"),
        ("zai/glm-4.5-air", "GLM 4.5 Air", "vercel-ai-gateway"),
        ("zai/glm-4.5v", "GLM 4.5V", "vercel-ai-gateway"),
        ("zai/glm-4.6", "GLM 4.6", "vercel-ai-gateway"),
        ("zai/glm-4.7", "GLM 4.7", "vercel-ai-gateway"),
        ("zai/glm-4.7-flash", "GLM 4.7 Flash", "vercel-ai-gateway"),
        ("zai/glm-4.7-flashx", "GLM 4.7 FlashX", "vercel-ai-gateway"),
        ("zai/glm-5", "GLM 5", "vercel-ai-gateway"),
        ("zai/glm-5-turbo", "GLM 5 Turbo", "vercel-ai-gateway"),
        ("zai/glm-5.1", "GLM 5.1", "vercel-ai-gateway"),
        ("zai/glm-5v-turbo", "GLM 5V Turbo", "vercel-ai-gateway"),
        ("zai/glm-4.5", "GLM-4.5", "vercel-ai-gateway"),
        ("zai/glm-4.6v", "GLM-4.6V", "vercel-ai-gateway"),
        ("zai/glm-4.6v-flash", "GLM-4.6V-Flash", "vercel-ai-gateway"),
        ("openai/gpt-5-chat", "GPT 5 Chat", "vercel-ai-gateway"),
        ("openai/gpt-5.1-codex-max", "GPT 5.1 Codex Max", "vercel-ai-gateway"),
        ("openai/gpt-5.1-codex-mini", "GPT 5.1 Codex Mini", "vercel-ai-gateway"),
        ("openai/gpt-5.1-thinking", "GPT 5.1 Thinking", "vercel-ai-gateway"),
        ("openai/gpt-5.2", "GPT 5.2", "vercel-ai-gateway"),
        ("openai/gpt-5.2-pro", "GPT 5.2 ", "vercel-ai-gateway"),
        ("openai/gpt-5.2-chat", "GPT 5.2 Chat", "vercel-ai-gateway"),
        ("openai/gpt-5.2-codex", "GPT 5.2 Codex", "vercel-ai-gateway"),
        ("openai/gpt-5.3-codex", "GPT 5.3 Codex", "vercel-ai-gateway"),
        ("openai/gpt-5.4", "GPT 5.4", "vercel-ai-gateway"),
        ("openai/gpt-5.4-mini", "GPT 5.4 Mini", "vercel-ai-gateway"),
        ("openai/gpt-5.4-nano", "GPT 5.4 Nano", "vercel-ai-gateway"),
        ("openai/gpt-5.4-pro", "GPT 5.4 Pro", "vercel-ai-gateway"),
        ("openai/gpt-5.5", "GPT 5.5", "vercel-ai-gateway"),
        ("openai/gpt-5.5-pro", "GPT 5.5 Pro", "vercel-ai-gateway"),
        ("openai/gpt-oss-20b", "GPT OSS 120B", "vercel-ai-gateway"),
        ("openai/gpt-oss-safeguard-20b", "GPT OSS Safeguard 20B", "vercel-ai-gateway"),
        ("openai/gpt-4-turbo", "GPT-4 Turbo", "vercel-ai-gateway"),
        ("openai/gpt-4.1", "GPT-4.1", "vercel-ai-gateway"),
        ("openai/gpt-4.1-mini", "GPT-4.1 mini", "vercel-ai-gateway"),
        ("openai/gpt-4.1-nano", "GPT-4.1 nano", "vercel-ai-gateway"),
        ("openai/gpt-4o", "GPT-4o", "vercel-ai-gateway"),
        ("openai/gpt-4o-mini", "GPT-4o mini", "vercel-ai-gateway"),
        ("openai/gpt-5", "GPT-5", "vercel-ai-gateway"),
        ("openai/gpt-5-mini", "GPT-5 mini", "vercel-ai-gateway"),
        ("openai/gpt-5-nano", "GPT-5 nano", "vercel-ai-gateway"),
        ("openai/gpt-5-pro", "GPT-5 pro", "vercel-ai-gateway"),
        ("openai/gpt-5-codex", "GPT-5-Codex", "vercel-ai-gateway"),
        ("openai/gpt-5.1-instant", "GPT-5.1 Instant", "vercel-ai-gateway"),
        ("openai/gpt-5.1-codex", "GPT-5.1-Codex", "vercel-ai-gateway"),
        ("openai/gpt-5.3-chat", "GPT-5.3 Chat", "vercel-ai-gateway"),
        ("xai/grok-3", "Grok 3 Beta", "vercel-ai-gateway"),
        ("xai/grok-3-fast", "Grok 3 Fast Beta", "vercel-ai-gateway"),
        ("xai/grok-3-mini", "Grok 3 Mini Beta", "vercel-ai-gateway"),
        ("xai/grok-3-mini-fast", "Grok 3 Mini Fast Beta", "vercel-ai-gateway"),
        ("xai/grok-4", "Grok 4", "vercel-ai-gateway"),
        ("xai/grok-4-fast-non-reasoning", "Grok 4 Fast Non-Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4-fast-reasoning", "Grok 4 Fast Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4.1-fast-non-reasoning", "Grok 4.1 Fast Non-Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4.1-fast-reasoning", "Grok 4.1 Fast Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4.20-non-reasoning-beta", "Grok 4.20 Beta Non-Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4.20-reasoning-beta", "Grok 4.20 Beta Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4.20-multi-agent-beta", "Grok 4.20 Multi Agent Beta", "vercel-ai-gateway"),
        ("xai/grok-4.20-multi-agent", "Grok 4.20 Multi-Agent", "vercel-ai-gateway"),
        ("xai/grok-4.20-non-reasoning", "Grok 4.20 Non-Reasoning", "vercel-ai-gateway"),
        ("xai/grok-4.20-reasoning", "Grok 4.20 Reasoning", "vercel-ai-gateway"),
        ("xai/grok-code-fast-1", "Grok Code Fast 1", "vercel-ai-gateway"),
        ("prime-intellect/intellect-3", "INTELLECT 3", "vercel-ai-gateway"),
        ("kwaipilot/kat-coder-pro-v2", "Kat Coder Pro V2", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2-0905", "Kimi K2 0905", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2", "Kimi K2 Instruct", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2-thinking", "Kimi K2 Thinking", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2-thinking-turbo", "Kimi K2 Thinking Turbo", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2-turbo", "Kimi K2 Turbo", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2.5", "Kimi K2.5", "vercel-ai-gateway"),
        ("moonshotai/kimi-k2.6", "Kimi K2.6", "vercel-ai-gateway"),
        ("meta/llama-3.1-70b", "Llama 3.1 70B Instruct", "vercel-ai-gateway"),
        ("meta/llama-3.1-8b", "Llama 3.1 8B Instruct", "vercel-ai-gateway"),
        ("meta/llama-3.2-11b", "Llama 3.2 11B Vision Instruct", "vercel-ai-gateway"),
        ("meta/llama-3.2-90b", "Llama 3.2 90B Vision Instruct", "vercel-ai-gateway"),
        ("meta/llama-3.3-70b", "Llama 3.3 70B Instruct", "vercel-ai-gateway"),
        ("meta/llama-4-maverick", "Llama 4 Maverick 17B Instruct", "vercel-ai-gateway"),
        ("meta/llama-4-scout", "Llama 4 Scout 17B Instruct", "vercel-ai-gateway"),
        ("meituan/longcat-flash-chat", "LongCat Flash Chat", "vercel-ai-gateway"),
        ("inception/mercury-2", "Mercury 2", "vercel-ai-gateway"),
        ("inception/mercury-coder-small", "Mercury Coder Small Beta", "vercel-ai-gateway"),
        ("xiaomi/mimo-v2.5", "MiMo M2.5", "vercel-ai-gateway"),
        ("xiaomi/mimo-v2-flash", "MiMo V2 Flash", "vercel-ai-gateway"),
        ("xiaomi/mimo-v2-pro", "MiMo V2 Pro", "vercel-ai-gateway"),
        ("xiaomi/mimo-v2.5-pro", "MiMo V2.5 Pro", "vercel-ai-gateway"),
        ("minimax/minimax-m2", "MiniMax M2", "vercel-ai-gateway"),
        ("minimax/minimax-m2.1", "MiniMax M2.1", "vercel-ai-gateway"),
        ("minimax/minimax-m2.1-lightning", "MiniMax M2.1 Lightning", "vercel-ai-gateway"),
        ("minimax/minimax-m2.5", "MiniMax M2.5", "vercel-ai-gateway"),
        ("minimax/minimax-m2.5-highspeed", "MiniMax M2.5 High Speed", "vercel-ai-gateway"),
        ("minimax/minimax-m2.7", "Minimax M2.7", "vercel-ai-gateway"),
        ("minimax/minimax-m2.7-highspeed", "MiniMax M2.7 High Speed", "vercel-ai-gateway"),
        ("mistral/ministral-3b", "Ministral 3B", "vercel-ai-gateway"),
        ("mistral/ministral-8b", "Ministral 8B", "vercel-ai-gateway"),
        ("mistral/codestral", "Mistral Codestral", "vercel-ai-gateway"),
        ("mistral/mistral-medium", "Mistral Medium 3.1", "vercel-ai-gateway"),
        ("mistral/mistral-small", "Mistral Small", "vercel-ai-gateway"),
        ("nvidia/nemotron-nano-12b-v2-vl", "Nvidia Nemotron Nano 12B V2 VL", "vercel-ai-gateway"),
        ("nvidia/nemotron-nano-9b-v2", "Nvidia Nemotron Nano 9B V2", "vercel-ai-gateway"),
        ("openai/o1", "o1", "vercel-ai-gateway"),
        ("openai/o3", "o3", "vercel-ai-gateway"),
        ("openai/o3-pro", "o3 Pro", "vercel-ai-gateway"),
        ("openai/o3-deep-research", "o3-deep-research", "vercel-ai-gateway"),
        ("openai/o3-mini", "o3-mini", "vercel-ai-gateway"),
        ("openai/o4-mini", "o4-mini", "vercel-ai-gateway"),
        ("mistral/pixtral-12b", "Pixtral 12B 2409", "vercel-ai-gateway"),
        ("mistral/pixtral-large", "Pixtral Large", "vercel-ai-gateway"),
        ("alibaba/qwen-3-32b", "Qwen 3 32B", "vercel-ai-gateway"),
        ("alibaba/qwen3-coder-30b-a3b", "Qwen 3 Coder 30B A3B Instruct", "vercel-ai-gateway"),
        ("alibaba/qwen3-max-thinking", "Qwen 3 Max Thinking", "vercel-ai-gateway"),
        ("alibaba/qwen3.5-flash", "Qwen 3.5 Flash", "vercel-ai-gateway"),
        ("alibaba/qwen3.5-plus", "Qwen 3.5 Plus", "vercel-ai-gateway"),
        ("alibaba/qwen3.6-27b", "Qwen 3.6 27B", "vercel-ai-gateway"),
        ("alibaba/qwen-3.6-max-preview", "Qwen 3.6 Max Preview", "vercel-ai-gateway"),
        ("alibaba/qwen3.6-plus", "Qwen 3.6 Plus", "vercel-ai-gateway"),
        ("alibaba/qwen-3-235b", "Qwen3 235B A22b Instruct 2507", "vercel-ai-gateway"),
        ("alibaba/qwen3-coder", "Qwen3 Coder 480B A35B Instruct", "vercel-ai-gateway"),
        ("alibaba/qwen3-coder-next", "Qwen3 Coder Next", "vercel-ai-gateway"),
        ("alibaba/qwen3-coder-plus", "Qwen3 Coder Plus", "vercel-ai-gateway"),
        ("alibaba/qwen3-max", "Qwen3 Max", "vercel-ai-gateway"),
        ("alibaba/qwen3-max-preview", "Qwen3 Max Preview", "vercel-ai-gateway"),
        ("alibaba/qwen3-235b-a22b-thinking", "Qwen3 VL 235B A22B Thinking", "vercel-ai-gateway"),
        ("alibaba/qwen3-vl-thinking", "Qwen3 VL 235B A22B Thinking", "vercel-ai-gateway"),
        ("alibaba/qwen-3-14b", "Qwen3-14B", "vercel-ai-gateway"),
        ("alibaba/qwen-3-30b", "Qwen3-30B-A3B", "vercel-ai-gateway"),
        ("bytedance/seed-1.6", "Seed 1.6", "vercel-ai-gateway"),
        ("perplexity/sonar", "Sonar", "vercel-ai-gateway"),
        ("perplexity/sonar-pro", "Sonar Pro", "vercel-ai-gateway"),
        ("arcee-ai/trinity-large-preview", "Trinity Large Preview", "vercel-ai-gateway"),
        ("arcee-ai/trinity-large-thinking", "Trinity Large Thinking", "vercel-ai-gateway"),
        ("grok-2", "Grok 2", "xai"),
        ("grok-2-1212", "Grok 2 (1212)", "xai"),
        ("grok-2-latest", "Grok 2 Latest", "xai"),
        ("grok-2-vision", "Grok 2 Vision", "xai"),
        ("grok-2-vision-1212", "Grok 2 Vision (1212)", "xai"),
        ("grok-2-vision-latest", "Grok 2 Vision Latest", "xai"),
        ("grok-3", "Grok 3", "xai"),
        ("grok-3-fast", "Grok 3 Fast", "xai"),
        ("grok-3-fast-latest", "Grok 3 Fast Latest", "xai"),
        ("grok-3-latest", "Grok 3 Latest", "xai"),
        ("grok-3-mini", "Grok 3 Mini", "xai"),
        ("grok-3-mini-fast", "Grok 3 Mini Fast", "xai"),
        ("grok-3-mini-fast-latest", "Grok 3 Mini Fast Latest", "xai"),
        ("grok-3-mini-latest", "Grok 3 Mini Latest", "xai"),
        ("grok-4", "Grok 4", "xai"),
        ("grok-4-fast", "Grok 4 Fast", "xai"),
        ("grok-4-fast-non-reasoning", "Grok 4 Fast (Non-Reasoning)", "xai"),
        ("grok-4-1-fast", "Grok 4.1 Fast", "xai"),
        ("grok-4-1-fast-non-reasoning", "Grok 4.1 Fast (Non-Reasoning)", "xai"),
        ("grok-4.20-0309-non-reasoning", "Grok 4.20 (Non-Reasoning)", "xai"),
        ("grok-4.20-0309-reasoning", "Grok 4.20 (Reasoning)", "xai"),
        ("grok-beta", "Grok Beta", "xai"),
        ("grok-code-fast-1", "Grok Code Fast 1", "xai"),
        ("grok-vision-beta", "Grok Vision Beta", "xai"),
        ("glm-4.5-air", "GLM-4.5-Air", "zai"),
        ("glm-4.7", "GLM-4.7", "zai"),
        ("glm-5-turbo", "GLM-5-Turbo", "zai"),
        ("glm-5.1", "GLM-5.1", "zai"),
        ("glm-5v-turbo", "glm-5v-turbo", "zai"),
    ]
}

pub fn get_models_for_provider(provider: &str) -> Vec<(&'static str, &'static str)> {
    get_all_models()
        .into_iter()
        .filter(|(_, _, p)| p == &provider)
        .map(|(id, name, _)| (id, name))
        .collect()
}

pub fn get_providers() -> Vec<&'static str> {
    let mut providers: Vec<&str> = get_all_models()
        .into_iter()
        .map(|(_, _, p)| p)
        .collect();
    providers.sort();
    providers.dedup();
    providers
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_models_not_empty() {
        assert!(!get_all_models().is_empty());
    }

    #[test]
    fn test_providers_not_empty() {
        assert!(!get_providers().is_empty());
    }

    #[test]
    fn test_anthropic_models() {
        let anthropic = get_models_for_provider("anthropic");
        assert!(!anthropic.is_empty());
    }

    #[test]
    fn test_openai_models() {
        let openai = get_models_for_provider("openai");
        assert!(!openai.is_empty());
    }
}
