//! Build script: scans pi-core/providers/*.toml and writes an index file
//! that enumerates each provider TOML. The runtime registry uses `include_str!`
//! via this generated index to embed every provider definition into the binary.
//!
//! Adding a new provider is a two-step process:
//!   1. Drop a new `.toml` file into `pi-core/providers/`
//!   2. Rebuild (`cargo build`)
//!
//! Runtime-only additions (no rebuild required) are supported via
//! `~/.pi/providers/*.toml` and `.pi/providers/*.toml` (project-local).

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let providers_dir = manifest_dir.join("providers");

    println!("cargo:rerun-if-changed=providers");
    println!("cargo:rerun-if-changed=build.rs");

    let mut toml_files: Vec<String> = Vec::new();

    if providers_dir.is_dir() {
        let entries = fs::read_dir(&providers_dir)
            .unwrap_or_else(|e| panic!("read_dir {:?}: {}", providers_dir, e));
        for entry in entries {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("toml") {
                let name = path
                    .file_name()
                    .and_then(|s| s.to_str())
                    .expect("utf8 filename")
                    .to_string();
                println!("cargo:rerun-if-changed=providers/{}", name);
                toml_files.push(name);
            }
        }
    }

    toml_files.sort();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let index_path = out_dir.join("providers_index.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. Do not edit.\n");
    code.push_str("pub static EMBEDDED_PROVIDERS: &[(&str, &str)] = &[\n");
    for name in &toml_files {
        // Each entry: (filename, embedded content)
        code.push_str(&format!(
            "    (\"{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/providers/{name}\"))),\n"
        ));
    }
    code.push_str("];\n");

    fs::write(&index_path, code).unwrap_or_else(|e| panic!("write {:?}: {}", index_path, e));

    println!(
        "cargo:warning=pi-core: embedded {} provider TOML file(s)",
        toml_files.len()
    );
}
